== 체크리스트 아이템 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

체크리스트 아이템 등록, 수정, 삭제, 조회가 가능합니다.
관련된 모든 요청에서 사용자 정보 식별을 위해 ``Header``의 ``Authorization``에 사용자의 ``액세스 토큰``을 포함시켜야 합니다.

=== 체크리스트 아이템 등록

체크리스트 아이템 등록이 가능하며 필요한 경우 체크리스트 서브 아이템과 한꺼번에 등록할 수도 있습니다.

체크리스트 아이템의 ``title``을 제외한 나머지 정보는 필수 값이 아닙니다.

operation::checklist/item/checklist-item-create/[snippets="http-request,request-fields,http-response,response-fields-data"]

=== 체크리스트 아이템 상세 조회

체크리스트 아이템 항목에 대한 상세 조회가 가능하며, 연결되어 있는 체크리스트 서브 아이템의 정보도 함께 응답 데이터에 포함됩니다.

operation::checklist/item/checklist-item-detail/[snippets="http-request,path-parameters,http-response,response-fields-data"]

=== 체크리스트 아이템 수정

체크리스트 아이템 및 연결되어 있는 체크리스트 서브 아이템의 수정이 가능합니다.
``PUT`` 메소드를 사용하기 때문에 수정을 원하는 체크리스트 아이템 및 서브 아이템의 ``전체 데이터``를 모두 포함하여 요청해야 합니다.

operation::checklist/item/checklist-item-modify/[snippets="http-request,path-parameters,request-fields,http-response,response-fields-data"]

=== 체크리스트 아이템 삭제

체크리스트 아이템 삭제가 가능합니다.
체크리스트 아이템을 삭제할 경우 연결되어 있는 서브 아이템도 함께 삭제됩니다.

operation::checklist/item/checklist-item-withdraw/[snippets="http-request,path-parameters,http-response"]