== 계약서 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

계약서 등록, 수정, 삭제, 조회가 가능합니다.
관련된 모든 요청에서 사용자 정보 식별을 위해 ``Header``의 ``Authorization``에 사용자의 ``액세스 토큰``을 포함시켜야 합니다.

=== 계약서 상세 조회

계약서 상세 조회가 가능합니다.

operation::contract/contract-detail/[snippets="http-request,path-parameters,http-response,response-fields-data"]

=== 계약서 리스트 조회

사용자가 등록한 계약서 리스트 조회가 가능합니다.
계약 날짜 순으로 정렬된 데이터가 전달됩니다.

operation::contract/get-contract-list/[snippets="http-request,http-response,response-fields-data"]

=== 계약서 등록

계약서 파일과 내용 등록이 가능합니다.

계약 상태는 다음 4가지 값만 등록 가능합니다.

- 계약 완료: COMPLETE
- 계약 중: IN_PROGRESS
- 구두 계약: VERBAL
- 가계약: PROVISIONAL

``multipart/form-data`` 로 ``file``과 ``data``를 포함하여 요청을 보내야 합니다.

operation::contract/create-contract/[snippets="http-request,request-parts,request-part-data-fields,http-response,response-fields-data"]

=== 계약서 파일 수정

계약서에 들어가는 파일을 수정할 수 있습니다.
파일 수정은 ``multipart/form-data`` 사용을 위해 ``POST`` 방식을 이용합니다.

operation::contract/modify-contract-file/[snippets="http-request,path-parameters,request-parts,http-response,response-fields-data"]

=== 계약서 내용 수정

파일을 제외한 계약서 내용에 대한 수정이 가능합니다.
``PUT`` 메소드를 사용하기 때문에 수정을 원하는 계약서의 ``전체 데이터(파일 정보 제외)``를 모두 포함하여 요청해야 합니다.

operation::contract/modify-contract/[snippets="http-request,path-parameters,request-fields,http-response,response-fields-data"]

=== 계약서 삭제

계약서 삭제가 가능하며, AWS S3 Storage에 저장되어 있는 계약서 파일도 함께 삭제됩니다.

operation::contract/contract-withdraw/[snippets="http-request,path-parameters,http-response"]